FROM node:20-alpine

WORKDIR /app

# Install dumb-init
RUN apk add --no-cache dumb-init

# Copy package files
COPY package*.json ./

# Copy source
COPY apps/scraper-service ./apps/scraper-service
COPY packages ./packages

# Install dependencies
RUN npm ci

ENTRYPOINT ["dumb-init", "--"]

# Development command
CMD ["npm", "run", "dev", "--workspace", "apps/scraper-service"]
