version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dropship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ['5432:5432']

  redis-node-1:
    image: redis:7
    command: ["redis-server", "--port", "6379", "--appendonly", "yes"]
    ports: ['6379:6379']

  redis-node-2:
    image: redis:7
    command: ["redis-server", "--port", "6380", "--appendonly", "yes"]
    ports: ['6380:6380']

  redis-node-3:
    image: redis:7
    command: ["redis-server", "--port", "6381", "--appendonly", "yes"]
    ports: ['6381:6381']

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: ['9200:9200']

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ['9092:9092']
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    ports: ['8123:8123', '9000:9000']

  prometheus:
    image: prom/prometheus
    ports: ['9090:9090']

  grafana:
    image: grafana/grafana
    ports: ['3002:3000']
